name: cursor-runpod-deploy smoke

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Root deps (optional)
      - name: Install root deps (if any)
        run: |
          if [ -f package.json ]; then
            if [ -f pnpm-lock.yaml ]; then
              corepack enable
              pnpm i --frozen-lockfile || pnpm i
            elif [ -f yarn.lock ]; then
              corepack enable
              yarn install --immutable || yarn install
            else
              if [ -f package-lock.json ]; then npm ci; else npm install; fi
            fi
          fi

      # --- Build the MCP package so dist/ exists ---
      - name: Build tools/runpod-mcp
        working-directory: tools/runpod-mcp
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm i --frozen-lockfile || pnpm i
            pnpm build || npx tsc -p tsconfig.json
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --immutable || yarn install
            yarn build || npx tsc -p tsconfig.json
          else
            if [ -f package-lock.json ]; then npm ci; else npm install; fi
            npm run build || npx tsc -p tsconfig.json
          fi

      - name: Sanity — help output
        run: node deploy.js --help

      - name: Sync deploy single file
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
        run: |
          node deploy.js ${{ secrets.RUNPOD_ENDPOINT_ID }} ./test-hello.py -p test-hello.py | tee output.txt
          grep -E "Status: *COMPLETED" output.txt

      - name: Async deploy directory (smoke)
        if: always()
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
        run: |
          mkdir -p tmpdir && cp test-hello.py tmpdir/main.py
          node deploy.js ${{ secrets.RUNPOD_ENDPOINT_ID }} ./tmpdir --async || true
